spring.application.name=facility-booking-system

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:facilitydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Console at http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Show SQL queries in terminal for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Ensures data.sql runs after Hibernate initializes tables
spring.jpa.defer-datasource-initialization=true

# Recreate schema on startup
spring.jpa.hibernate.ddl-auto=update

# Google oAuth2 Client configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=TRACE

# JWT Configuration (Use a 256-bit secret key in production)
jwt.secret=${JWT_SECRET_KEY}
jwt.expiration=86400000

# React Frontend URL (For OAuth2 redirect after success)
app.oauth2.redirectUri=http://localhost:5173/oauth2/redirect